### ISSUE TITLE
trim is broken in omnipaxos_storage::persistent_storage

### ISSUE THREAD

**Issue by soruh** [haraldng/omnipaxos#129]
I was planning to write my own implementation of the `Storage` trait, but as the details on how to implement it are not particularly clear I wrote some testcases against the existing implementations in `omnipaxos_storage` to compare my implementation against them. (https://gitea.h.glsys.de/soruh/validate_omnipaxos_storage).

Running these tests I noticed that on the current `master`  (The implementations in `0.2.2` have several other problems) the trim implementation of `omnipaxos_storage::persistent_storage` doesn't seem to set the length of the log correctly:

This fails for `PersistentStorage` but succeeds for `MemoryStorage`:
```rust
// --- ommited ---
let entries = random_entries(6);

storage.append_entries(entries.clone())?;
assert_eq!(storage.get_log_len()?, 6, "log has the correct length after first insert");

storage.trim(3)?;
assert_eq!(storage.get_log_len()?, 3, "log has the correct length after trim");
// --- ommited ---
```

```rust
running 1 test
test tests::persistent::functionality_after_trim ... FAILED

failures:

---- tests::persistent::functionality_after_trim stdout ----
thread 'tests::persistent::functionality_after_trim' panicked at src/lib.rs:119:5:
assertion `left == right` failed: log has the correct length after trim
  left: 6
 right: 3
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    tests::persistent::functionality_after_trim

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 15 filtered out; finished in 0.01s
```

Perhaps it would be a good Idea to properly document what exactly the methods of the `Storage` trait should do including their effect on the length of the log and how the index numbering should continue.

**Comment by haraldng** [comment]
The test fails because `PersistentStorage::get_log_len()` internally uses the `compacted_idx` to calculate the log length, and in the test code,  `trim()` is called without doing `set_compacted_idx()`. 

The `PersistentStorage` (or any `Storage` implementation) is not intended to be used directly. Instead, it should only be used internally by the [`OmniPaxos`](https://docs.rs/omnipaxos/latest/omnipaxos/struct.OmniPaxos.html) struct. This is because OmniPaxos uses internal logic to interact with the `Storage` to make sure the state of it is correct. For instance, trimming (e.g., if you call [OmniPaxos::trim()](https://docs.rs/omnipaxos/latest/omnipaxos/struct.OmniPaxos.html#method.trim)), will internally perform both `Storage::trim()` and `Storage::set_compacted_idx()`, which means that if OmniPaxos then performs get_log_len(), it will be correct. This is why we currently perform all storage-related tests in `omnipaxos`.

I do agree that the documentation for the `Storage` trait could be a bit more clear, and more importantly, we should have unit tests for our storage implementations that will make it easier for users to easier understand how it should be implemented and test their implementations (even from outside the OmniPaxos struct). I will create an issue for it.

**Comment by haraldng** [comment]
The test fails because `PersistentStorage::get_log_len()` internally uses the `compacted_idx` to calculate the log length, and in the test code,  `trim()` is called without doing `set_compacted_idx()`.  This is fine when we use `PersistentStorage` for OmniPaxos because we always update the compacted index when trimming. In general, `PersistentStorage` (and any `Storage` implementation) is not intended to be used directly. 

However, I do agree that the documentation for the `Storage` trait could be a bit more clear, and more importantly, we should have unit tests for our storage implementations that will make it easier for users to understand how it should be implemented and test their implementations (even from outside the OmniPaxos struct). I will create an issue for it (#130).

**Comment by soruh** [comment]
Thank you! Sorry for the confusion.
