### ISSUE TITLE
Introduce applied_index variable?

### ISSUE THREAD

**Issue by kevin-harrison** [haraldng/omnipaxos#131]
Right now we incorrectly assume that it is safe to trim decided entries in the log. The point at which it is ok to trim an entry is when it has been applied to the local state machine (which happens outside the scope of OmniPaxos). What we should really care about is the `applied_idx` not the `decided_idx`.  A user of OmniPaxos can still guarantee safety by ensuring they have applied all decided entries before trimming, which ensures `applied_idx = decided_idx`. But it is probably less error prone to instead create a public function that allows a user of OmniPaxos to inform us what the current `applied_idx` is. With the `applied_idx` we can also create a nicer API for a user to request decided-but-not-applied-entries instead of `read_decided_suffix`.

Furthermore if a user wants to efficiently implement crash-recovery they will need to persist this `applied_idx` (see section 3.8 of the [Raft dissertation](https://web.stanford.edu/~ouster/cgi-bin/papers/OngaroPhD.pdf)). So it could be nice to handle this persistence for them. 

Similar complications have to be considered when it comes to snapshotting. If a user calls `read_decided_suffix` in order to apply new entries and gets a `LogEntry::Snapshotted(Snapshot)` they must reset their ENTIRE state and replace it with the applied snapshot. This scenario can occur outside of the control of the user since Prepare phase syncing can cause decided-but-not-applied entries to be snapshotted. Therefore I think it makes sense to rethink snapshotting and syncing in the context of this `applied_idx`.

**Comment by haraldng** [comment]
> Right now we incorrectly assume that it is safe to trim decided entries in the log.

This is not entirely true. Currently, the library never trims unless it is called by the user. If the user calls it, we assume that they really want to get rid of those entries (i.e., they don't need it in their application anymore). The only additional safety mechanism we provide is to check that all servers have really decided up to the trim index argument (otherwise the lagging servers will not be able to catch up those trimmed entries).

I think this boils down to how much we want OmniPaxos to be a log library vs. an RSM library. I'm a bit reluctant towards introducing an `applied_index` variable because imo this is the user's responsibility. OmniPaxos' role is to be a distributed log and the log shouldn't keep track of how far you've read in it, this should be tracked by the user themselves. 

I do agree that there are some benefits we could get from introducing `applied_index`, such as the case you describe with the snapshot. But it also comes at the potential cost of performance and more complexity (how do we guarantee the atomicity of OmniPaxos' applied_index and the application state). If we would handle these things, I think that should be another library built on OmniPaxos that is an RSM library that stores and modifies the state directly rather than a log library like OmniPaxos.

**Comment by kevin-harrison** [comment]
Right, if the user does everything correctly there will be no safety issues. But we should probably show how to properly handle snapshotted entries in `omnipaxos-rocksdb-tutorial`. This is what is currently done with isn't safe:
```rust
    fn update_database(&self, decided_entries: Vec<LogEntry<KVCommand>>) {
        for entry in decided_entries {
            match entry {
                LogEntry::Decided(cmd) => {
                    self.database.handle_command(cmd);
                }
                _ => {}
            }
        }
    }
```

**Comment by haraldng** [comment]
Closing this issue here. Feel free to submit issue or PR to the [tutorial repo](https://github.com/haraldng/omnipaxos-rocksdb-tutorial).
